<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top"><?= $this->partial('layout/top_menu');?></div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <?= $this->partial('layout/footer');?>
            </footer>
        </div>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile('/js/json.js')
                                      ->prependFile('/js/bootstrap.js')
        						      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js') ?>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
