<div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Form Generator</a>
        <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/formgen/create">Create Forms</a></li>
            </ul>
        </div>
    </div>
</div>