<?= '<h3>'.$this->result->name.'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?= $this->result->id; ?>">
	<ul class="nav nav-list">
        <li>
            <label>Drop Down Name</label>
            <input type="text" name="input_name" maxlength="255" value="name">
        </li>
		<li>
			<label>Replace Label Text</label>
			<input type="text" name="text_label" maxlength="255" value="Drop Down">
		</li>
        <li>
            <fieldset class="choices">
                <p><?= $this->result->name; ?> Choices</p>
                <ul class="element_choices">
                    <?php for($i=0; $i<$this->result->length; $i++){ ?>
                    <li class="duplicate_input">
                        <input class="input-small" type="text" value="Dropdown" name="rem<?php echo $i;?>">
                        <button class="btn btn-mini" id="rem<?php echo $i;?>">remove</button>
                        <button class="btn btn-mini" id="def<?php echo $i;?>">set default</button>
                    </li>
                    <?php } ?>
                    <button class="btn btn-mini" id="add_new_dropdown_field">add new field</button>
                </ul>
            </fieldset>
        </li><br>
        <li>
            <label>Validation Message</label>
            <input type="text" name="number_notinarray" maxlength="255" value="Please select your gender !">
        </li>
        <li>
            <label>Class</label>
            <input type="text" name="number_class" maxlength="255" placeholder="class1 class2..">
        </li>
        <li>
            <label>Id</label>
            <input type="text" name="number_id" maxlength="255" placeholder="custom id">
        </li>
		<li>
			<br><button class="btn btn-primary" id="add_form_dropdown">Save</button>
		</li>
	</ul>
</form>

<?= '<code>'.$this->result->id.'</code>'; ?>