<?= '<h3>'.$this->result->name.'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?= $this->result->id; ?>">
	<ul class="nav nav-list">
        <li>
            <label>Input Name</label>
            <input type="text" name="input_name" maxlength="255" value="number">
        </li>
		<li>
			<label>Replace Label Text</label>
			<input type="text" name="text_label" maxlength="255" value="Number Label">
		</li>
		<li>
			<label>Placeholder Text</label>
			<input type="text" name="placeholder_text" maxlength="255" value="1234567890">
		</li>
		<li>
			<label>Required</label>
			<select name="required">
				<option value="no">No</option>
				<option value="yes">Yes</option>
			</select>
		</li>
        <li>
			<label>Number Validation</label>
			<select name="valid_type">
				<option value="digits">Digits (1, 14)</option>
				<option value="float">Float (5.3, 6,8)</option>
				<option value="int">Int (-25, 23)</option>
			</select>
		</li>
        <li>
            <label>Use html5</label>
            <input type="checkbox" name="number_html5" value="0">
            <i>(if used, this will add type="number" and validate only digits)</i>
        </li><br>
        <li>
            <label>Validate between</label>
            <input type="number" name="number_min" class="input-small" placeholder="min">
            <input type="number" name="number_max" class="input-small" placeholder="max">
            <p>number of characters.</p>
        </li>
        <li>
            <label>String Length</label>
            <input type="number" name="number_min_str" class="input-small" placeholder="min">
            <input type="number" name="number_max_str" class="input-small" placeholder="max">
        </li>
        <li>
            <label>Class</label>
            <input type="text" name="number_class" maxlength="255" placeholder="class1 class2..">
        </li>
        <li>
            <label>Id</label>
            <input type="text" name="number_id" maxlength="255" placeholder="custom id">
        </li>
		<li>
			<button class="btn btn-primary" id="add_form_number">Save</button>
		</li>
	</ul>
</form>

<?= '<code>'.$this->result->id.'</code>'; ?>