<?= '<h3>'.$this->result->name.'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?= $this->result->id; ?>">
	<ul class="nav nav-list">
		<li>
			<label>Verify Password Name</label>
			<input type="text" name="input_name" maxlength="255" value="password_verify">
		</li>
        <li>
			<label>Replace Label Text</label>
			<input type="text" name="text_label" maxlength="255" value="Password">
		</li>
		<li>
			<label>Placeholder Text</label>
			<input type="text" name="placeholder_text" maxlength="255" value="Verify Password Here...">
		</li>
        <li>
			<label>Token</label>
			<input type="text" name="token" maxlength="255" value="password">
		</li>
        <li>
            <label>Class</label>
            <input type="text" name="number_class" maxlength="255" placeholder="class1 class2..">
        </li>
        <li>
            <label>Id</label>
            <input type="text" name="number_id" maxlength="255" placeholder="custom id">
        </li>
		<li>
			<button class="btn btn-primary" id="add_form_password_verify">Save</button>
		</li>
	</ul>
</form>

<?= '<code>'.$this->result->id.'</code>'; ?>