<?php

$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('formgen/test'));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('csrf'));
echo $this->formHidden($form->get('hidden'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('number'));
echo $this->formRow($form->get('radio'));
echo $this->formRow($form->get('appointment_date'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password1'));
echo $this->formRow($form->get('password_verify'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();