<?= '<h3>'.$this->result->name.'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?= $this->result->id; ?>">
	<ul class="nav nav-list">
		<li>
			<label>File Upload Name</label>
			<input type="text" name="input_name" maxlength="255" value="file">
		</li>
        <li>
			<label>Replace Label Text</label>
			<input type="text" name="text_label" maxlength="255" value="Form Upload">
		</li>
		<li>
			<label>Required</label>
			<select name="required">
				<option value="no">No</option>
				<option value="yes">Yes</option>
			</select>
		</li>
        <li>
            <label>Class</label>
            <input type="text" name="number_class" maxlength="255" placeholder="class1 class2..">
        </li>
        <li>
            <label>Id</label>
            <input type="text" name="number_id" maxlength="255" placeholder="custom id">
        </li>
		<li>
			<button class="btn btn-primary" id="add_form_text">Save</button>
		</li>
	</ul>
</form>

<?= '<code>'.$this->result->id.'</code>'; ?>