<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Form\Module'                        => __DIR__ . '/Module.php',
    'Form\Controller\IndexController' => __DIR__ . '/src/Form/Controller/IndexController.php',
    'FormTest\Framework\TestCase'        => __DIR__ . '/tests/Form/Framework/TestCase.php',
    'FormTest\SampleTest'                => __DIR__ . '/tests/Form/SampleTest.php',
);
