<div class="hero-unit">
    <h1>Zend Framework 2 Form Generator</h1>
    <p>Simple form generator</p>
    <p>
        <a class="btn btn-success btn-large" href="https://github.com/patrioticcow/Zend-Form" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 Form Generator on GitHub') ?></a>
    </p>
    <p>
        <a class="btn btn-success btn-large" href="/formgen/create"><?php echo $this->translate('Start Here') ?></a>
    </p>
</div>

<div class="row">

    <div class="span4">
        <h2>Beta Release</h2>
        <p>The form generator is not fully completed. It generates the <b>form class</b>, <b>form validator class</b>, <b>controller action</b>, <b>view</b>, <b>view helper</b></p>

        <h2>To do</h2>
        <p>1. there are some saving issues that need to be addressed.</p>
        <p>2. Finish the View Helper</p>
        <p>3. Add Form Annotations</p>
        <p>more..</p>
    </div>

   <div class="span8">
       <h2>How does it work</h2>
       <p>To use the form generator make sure you fill up the <code>Form Properties</code>.</p>
       <p>Also when you add a new field make sure you click the <code>Save</code> button before generating the code.</p>
       <p>A full utorial comming shortly</p>

       <h2>About ZF2 Form Generator</h2>
       <p>This form generator is intended to easy the creations of forms in Zend Framework 2</p>
   </div>
</div>
